### ISSUE TITLE
Install method in readme.md seems inaccurate

### ISSUE THREAD

**Issue by BigRoy** [pyblish/pyblish-win#11]
There seems to be a bug in the `readme.md` that describes how to install pyblish-win from the repository.

It states:

```
# Quick-start installation
$ git clone https://github.com/pyblish/pyblish-win.git
$ pyblish-win\install --global
$ pyblish-win\bin\pyblish-qml
```

I didn't need the global option for the installer and tried:

```
$ git clone https://github.com/pyblish/pyblish-win.git
$ pyblish-win\install
```

I'm getting the following error:

```
fatal: Not a git repository (or any of the parent directories): .git
```

It seems I need to be within the repository for installation to succeed. So this worked:

```
$ git clone https://github.com/pyblish/pyblish-win.git
$ cd pyblish-win
$ install
```

**Comment by mottosso** [comment]
Thanks, could you PR this? I'll get it merged asap.

**Comment by BigRoy** [comment]
Sure, having a look in a bit.
