### ISSUE TITLE
gitignore of *.pyc files

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-win#4]
minor issue of having `*.pyc` files ready to stage

**Comment by mottosso** [comment]
Say what? :octopus:

**Comment by tokejepsen** [comment]
Updating with SourceTree (maybe I shouldn't?) and all the *.pyc files are not ignored.

**Comment by mottosso** [comment]
How do you mean updating with SourceTree? You mean you are pulling the latest from GitHub?

**Comment by tokejepsen** [comment]
yeah, pulling with SourceTree from GitHub

**Comment by mottosso** [comment]
Pulling doesn't delete any files. You'll need to reset your repo to it's original state, that will remove anything that wasn't part of the original. Then you can pull.

Have a look at how [`update.bat`](https://github.com/pyblish/pyblish-win/blob/master/update.bat) does it.

**Comment by tokejepsen** [comment]
alright, will just ignore it for now then.
