### ISSUE TITLE
install.bat reports success even without git

### ISSUE THREAD

**Issue by jedfrechette** [pyblish/pyblish-win#5]
If git isn't found on the PATH when running install.bat the script still reports success even though none of the submodules get checked out.

**Comment by mottosso** [comment]
Thanks @jedfrechette, having a look at this now.

**Comment by mottosso** [comment]
Should be ok now, here's how it works, feel free to keep commenting here if it you still experience the same problem.

``` bash
$ git clone https://github.com/pyblish/pyblish-win.git
$ cd pyblish-win
$ install
```

![untitled](https://cloud.githubusercontent.com/assets/2152766/8879082/55f0ed1a-322f-11e5-9322-b0947a68067e.gif)

**More options**

Pass `--help` for more options.

![image](https://cloud.githubusercontent.com/assets/2152766/8878674/bc7f1276-322c-11e5-8273-0b544f9afec2.png)
