### ISSUE TITLE
pythonw.bat

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-win#8]
Could we add a pythonw.bat to execute python script in an pyblish-win environment?

```
@echo off
set PYTHONPATH=%~dp0..\pythonpath;%~dp0..\lib\python-qt5;%PYTHONPATH%
start "" "%~dp0..\lib\Python27\pythonw.exe" %*
```

**Comment by mottosso** [comment]
Sure, sounds good. Have you tested this?

**Comment by tokejepsen** [comment]
Yeah, using this atm here.

**Comment by mottosso** [comment]
Ok, consider it done. I'll add this to the next release.
